name: convml_tt

channels:
  - pytorch
  - fastai
  - defaults
  - conda-forge
dependencies:
  - pip<=19.0.0 # until PEP517 is fixed we can use pip v19.x, see https://github.com/SciTools/cartopy/issues/1270#issuecomment-458933013
  - python=3.7
  - boto3
  - cartopy
  - jupyter
  - matplotlib
  - netcdf4
  - tqdm
  - xarray
  - scikit-learn
  - pytorch=1.0.1
  - torchvision
  - cudatoolkit=9.0
  - Pillow=6.1
  # dependencies below are necessary for the `satdata` code which will
  # eventually be forked from `convml_tt`
  - esmpy
  - xesmf
  - pip:
    # satpy deps
    - satpy==0.12.0
    - esmpy
    - progressbar
    - fastai==1.0.53
    - seaborn
    - "git+https://github.com/leifdenby/satdata@v0.1.3#egg=satdata"
    - "git+https://github.com/leifdenby/convorg@v0.7.0#egg=convorg"
