name: convml_tt

channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.7
  - netcdf4
  - pytorch
  - pytorch-lightning
  - torchvision
  - cudatoolkit=9.0
  - Pillow=6.1
